url: https://www.rightinthemiddle.io
name: Right in the Middle
description: A grumpy geek and a clumsy assistant will make your ideas shine with a different way of presenting technical content.

encoding: utf-8

permalink: /episodes/:title

sass:
  style: compressed

plugins:
  - liquid-md5
